import './global.css';
import { lato } from './fonts';

export const metadata = {
  title: 'Welcome to ',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`theme-wilko ${lato.variable}`}>
      <body>{children}</body>
    </html>
  );
}
